--remote-components ejs:npm

--format "bestvideo[height<=1080][ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best"

--add-header "Origin: https://www.youtube.com/"

--use-postprocessor FFmpegCopyStream
--ppa CopyStream:"-c:v libx265 -c:a aac -f mp4"
-S ext:mp4:m4a

--write-thumbnail
--convert-thumbnails jpg

--write-sub
--sub-langs en
--write-auto-subs

--write-link