--remote-components ejs:npm

--add-header# "Origin: https://www.youtube.com/"

--live-from-start

--audio-format m4a

--write-thumbnail
--convert-thumbnails jpg

--write-sub
--sub-langs en
--write-auto-subs